service: appointmentfeedback

frameworkVersion: '2'

provider:
  name: aws
  runtime: go1.x

environment:
  NEO4J_TARGET: neo4j://localhost:7687

package:
  exclude:
    - ./**
  include:
    - ./bin/**

functions:
  hello:
    handler: bin/api
    events:
      - http:
          path: /
          method: ANY